config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root "friends#index"
  resources :friends
  # to 'update' get "devise#update#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
require 'elasticsearch/model'

class Friend < ApplicationRecord
    belongs_to :user
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    # Friend.__elasticsearch__.create_index!
    # Friend.Model                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
    # @friends = Friend.search('foobar').records
end
 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        #  belongs_to :role
        has_many :friends
  # enum role: [:user, :admin]
  # after_initialize :set_default_role, :if => :new_record?
  # def set_default_role
  #   self.role ||= :user
  # end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
         def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname,:DOB,:gender, :email, :password,:role)}
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname, :lastname,:DOB,:gender, :email, :password, :current_password,:role)}
         end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @friends = Friend.all
  end
  def show
  end
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build  
  end
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    if @friend.save
      redirect_to root_path
    else
    render :new
    end
  end
  def destroy
    if @friend.destroy
      redirect_to friends_path
    end
  end
  def edit
    @friend = Friend.find(params[:id])
end
  def update
    if @friend.update(friend_params)
      redirect_to root_path
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend" if @friend.nil?
  end
  private
  def set_friend
    @friend = Friend.find(params[:id])
  end
  def friend_params
    params.require(:friend).permit(:fullname, :body, :phone, :user_id)
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
    def index
        @roles = Role.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/friends/edit.html.erb
<%= form_with model: @friend do |form| %>
<div>
    <%=form.label :fullname%>
    <%=form.text_area :fullname%>
</div>
<div>
    <%=form.label :phone%>
    <%=form.text_area :phone%>
</div>
<div>
    <%=form.label :body%>
    <%=form.text_area :body%>
</div>
<div>
    <%= form.number_field :user_id ,id: :friend_user_id, class:"form-control",value:current_user.id , type: :hidden%>
</div>

<div>
    <%=form.submit%>
</div>
<% end %>

app/views/friends/index.html.erb
<% if current_user && current_user.role == "admin" %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Fullname</th>
                <th scope="col">Role</th>
                <th scope="col">Email</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <% User.all.each do |user|%>
            <tbody>
                <% if user.role == "user" %>
                    <td><%=user.firstname%></td>
                    <td><%=user.role%></td>
                    <td><%=user.email%></td>
                    <td><%=link_to 'Destroy', user,class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' }%></td>    
                <% end %>
            </tbody> 
        <% end %>
    </table>       
<% elsif current_user && current_user.role == "user" %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Fullname</th>
                <th scope="col">Phone</th>
                <th scope="col">Body</th>
                <% if user_signed_in? %>
                    <th scope="col">Action</th>
                <% end %>
            </tr>
        </thead>
        <% @friends.each do |item| %>
            <tbody>
                <tr>
                    <%if item.user == current_user%>
                        <td><%=item.fullname%></td>
                        <td><%=item.phone%></td>
                        <td><%=item.body%></td>
                        <td><a href = "/friends/<%=item.id%>",class="nav-link">Go To</a> 
                        <td><%= link_to 'Destroy', item,class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %></td></td>       
                    <% end %>
                    <% if !user_signed_in? %>
                        <td><%=item.fullname%></td>
                        <td><%=item.phone%></td>
                        <td><%=item.body%></td>
                    <% end %>
                </tr>
            </tbody>
        <% end %>
    </table>  
<% end %>

<% if user_signed_in? %>
    <%= link_to "New" ,new_friend_path%>
<% end %>    

app/views/friends/new.html.erb
<%= form_with model: @friend do |form| %>
<div>
    <%=form.label :fullname,class:"form-label"%>
    <%=form.text_area :fullname,class:"form-control"%>
</div>
<div>
    <%=form.label :phone,class:"form-label"%>
    <%=form.text_area :phone,class:"form-control"%>
</div>
<div>
    <%=form.label :body,class:"form-label"%>
    <%=form.text_area :body,class:"form-control"%>
</div>
<div>
    <%=form.number_field :user_id,id: :friend_user_id,value: current_user.id ,type: :hidden%>
</div>

<div>
    <%=form.submit class:"btn btn-success" %>
</div>
<% end %>

app/views/friends/show.html.erb
<h1><%=@friend.fullname%></h1>
<h1><%=@friend.body%></h1>
<h1><%=@friend.phone%></h1>
<h1><%=@friend.user_id%></h1>

<%= link_to "edti", edit_friend_path(@friend)%>
<%= link_to "destroy" ,@friend,method: :delete, data: { confirm: 'Are you sure?' }%>

app/views/layouts/_alerts.html.erb
<br/>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Ruby App',root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-2 mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home',root_path,class:"nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to 'Sign Out',destroy_user_session_path,method: :delete,class:"nav-link"%>
          </li>
          <li class="nav-item">
              <%= link_to 'Edit Profile',edit_user_registration_path,class:"nav-link"%>
          </li>     
          <% else %>
            <li class="nav-item">
                <%= link_to 'Sign Up',new_user_registration_path,class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign In',new_user_session_path,class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to 'Forgot Password',new_user_password_path,class:"nav-link"%>
            </li>
        <% end %>          
      </ul> 
    </div> 
  </nav>
    <% if notice %>
    <%=render 'layouts/alerts' %>    
  <% end %>
  <%= yield %>

</body>
</html>